//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tests()
        {
            this.Results = new ObservableList<Results>();
        }
    
        public int Id { get; set; }
        public string Theme { get; set; }
        public string Path { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public System.DateTime DateTime { get; set; }
        public int PassTimeSec { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableList<Results> Results { get; set; }
        public virtual Users Users { get; set; }
    }
}
